// Auto-generated by AIAnalyzer
module.exports = {
    matches: function(context) {
        // AI deduced this rule based on Fingerprint: Unknown
        if (context.fingerprintResult && context.fingerprintResult.player === "Unknown") return true;
        return false;
    }
};