"use strict";

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const PlayerInterfaceFactory = require('../players');

/**
 * HyperSnatch AI Analyzer (Self-Learning Extraction Engine)
 * Automatically discovers extraction patterns for unknown sites by analyzing DOM,
 * global variables, and network requests, then generates reusable extraction scripts.
 */
class AIAnalyzer {

    /**
     * Entry point to analyze a page context.
     * @param {Object} context The simulated or real execution context containing window, DOM, network events.
     * @returns {Object|null} Generated extraction rule or null if unsuccessful.
     */
    static analyze(context) {
        console.log(`[AIAnalyzer] Starting autonomous pattern discovery on ${context.url || 'unknown page'}...`);

        let targetStreamUrl = this._findTargetStream(context.networkLogs, context.dom);
        if (!targetStreamUrl) {
            console.log(`[AIAnalyzer] No viable media stream found in network/DOM traces. Cannot generate rule.`);
            return null;
        }

        console.log(`[AIAnalyzer] Target stream identified: ${targetStreamUrl}`);

        // Try heuristically via known players FIRST.
        const playerRule = this._deriveFromPlayerObjects(context.window, targetStreamUrl);
        if (playerRule) {
            this._generatePlugin(playerRule, context);
            return playerRule;
        }

        // Fallback to global variable search
        const globalRule = this._deriveFromGlobalVariables(context.window, targetStreamUrl);
        if (globalRule) {
            this._generatePlugin(globalRule, context);
            return globalRule;
        }

        // Fallback to DOM elements
        const domRule = this._deriveFromDOM(context.window.document, targetStreamUrl);
        if (domRule) {
            this._generatePlugin(domRule, context);
            return domRule;
        }

        console.log(`[AIAnalyzer] Failed to correlate ${targetStreamUrl} to a reproducible script pattern.`);
        return null;
    }

    /**
     * Generates a full 5-part plugin folder based on the deduced rule
     */
    static _generatePlugin(rule, context) {
        const pluginDir = path.join(__dirname, 'generated_plugins', rule.id);
        fs.mkdirSync(pluginDir, { recursive: true });

        const fingerprint = context.fingerprintResult ? context.fingerprintResult.player : 'Unknown';
        const mseCount = context.mseBuffers ? context.mseBuffers.length : 0;

        // 1. detect.js
        const detectCode = `// Auto-generated by AIAnalyzer
module.exports = {
    matches: function(context) {
        // AI deduced this rule based on Fingerprint: ${fingerprint}
        if (context.fingerprintResult && context.fingerprintResult.player === "${fingerprint}") return true;
        return false;
    }
};`;
        fs.writeFileSync(path.join(pluginDir, 'detect.js'), detectCode);

        // 2. extract.js
        const extractCode = `// Auto-generated by AIAnalyzer
module.exports = {
    extract: function(window, document) {
        ${rule.scriptPattern}
    }
};`;
        fs.writeFileSync(path.join(pluginDir, 'extract.js'), extractCode);

        // 3. resolve.js
        const resolveCode = `// Auto-generated by AIAnalyzer
module.exports = {
    resolve: function(url) {
        return url; // Identity function by default
    }
};`;
        fs.writeFileSync(path.join(pluginDir, 'resolve.js'), resolveCode);

        // 4. explanation.md
        const mdCode = `# Auto-Generated Extraction Rule: ${rule.id}
- **Strategy**: ${rule.strategy}
- **Target URL**: ${rule.sampleTarget}
- **Detected Player**: ${fingerprint}
- **MSE Buffers Intercepted**: ${mseCount}

This plugin was generated fully autonomously by tracing live variable state against network observables.
`;
        fs.writeFileSync(path.join(pluginDir, 'explanation.md'), mdCode);

        // 5. confidence.json
        const infoCode = JSON.stringify({
            id: rule.id,
            strategy: rule.strategy,
            confidence: rule.confidence,
            sample: rule.sampleTarget,
            generatedAt: Date.now()
        }, null, 2);
        fs.writeFileSync(path.join(pluginDir, 'confidence.json'), infoCode);

        console.log(`[AIAnalyzer] Dumped robust plugin structure to: ${pluginDir}`);
    }

    /**
     * Looks through network requests and raw DOM strings for .m3u8, .mpd, or .mp4 
     * that we want to build a rule around.
     */
    static _findTargetStream(networkLogs = [], dom = "") {
        // Priority 1: Network traces
        for (const log of networkLogs) {
            if (/\.(m3u8|mpd|mp4)(\?|$)/i.test(log.url)) {
                return log.url;
            }
        }

        // Priority 2: Regex sweeping the DOM string
        const regex = /https?:\/\/[^\s"'<>]+\.(m3u8|mpd|mp4)(?:\?[^\s"'<>]+)?/gi;
        const match = regex.exec(dom);
        if (match) return match[0];

        return null;
    }

    /**
     * Tries to find the target stream inside initialized player config objects
     * @returns {Object|null} The generated rule object
     */
    static _deriveFromPlayerObjects(windowObj, targetUrl) {
        // We leverage the PlayerInterfaceFactory built in the Ultra Core phase!
        const players = PlayerInterfaceFactory.extractAllAvailable(windowObj);

        for (const playerState of players) {
            for (const stream of playerState.streams) {
                if (stream.url === targetUrl || targetUrl.includes(stream.url)) {
                    console.log(`[AIAnalyzer] Correlated stream to ${playerState.player} configuration.`);

                    // Generate code that invokes the player heuristically
                    // We generate a deterministic ID / Rule schema
                    const scriptPattern = `
                        return (function() {
                            const p = require('../players/${playerState.player}');
                            const res = p.extract(window);
                            return res.streams.length > 0 ? res.streams[0].url : null;
                        })();
                    `;

                    return this._buildRulePayload('player_derivation', playerState.player, scriptPattern, targetUrl);
                }
            }
        }
        return null;
    }

    /**
     * Deep scans the window object to find which variable holds the target URL.
     */
    static _deriveFromGlobalVariables(windowObj, targetUrl) {
        // Recursive search function
        const findPath = (obj, target, currentPath = "window", depth = 0, seen = new Set()) => {
            if (depth > 4 || !obj || typeof obj !== 'object' || seen.has(obj)) return null;
            seen.add(obj);

            for (const [key, value] of Object.entries(obj)) {
                // Ignore DOM nodes heavily to save time
                if (value && value.nodeType) continue;

                const newPath = currentPath + (/\W/.test(key) ? `['${key}']` : `.${key}`);

                if (typeof value === 'string' && (value === target || target.includes(value))) {
                    return newPath;
                } else if (typeof value === 'object') {
                    const result = findPath(value, target, newPath, depth + 1, seen);
                    if (result) return result;
                }
            }
            return null;
        };

        const path = findPath(windowObj, targetUrl);
        if (path) {
            console.log(`[AIAnalyzer] Correlated stream to global object path: ${path}`);
            const scriptPattern = `return ${path};`;
            return this._buildRulePayload('global_variable', 'custom', scriptPattern, targetUrl);
        }

        return null;
    }

    /**
     * Scans DOM elements (e.g. <video src="...">, <source>) for the URL.
     */
    static _deriveFromDOM(documentObj, targetUrl) {
        if (!documentObj) return null;

        const videos = documentObj.querySelectorAll('video, source, a');
        for (const vid of videos) {
            if (vid.src === targetUrl || vid.href === targetUrl) {
                const selector = vid.id ? `#${vid.id}` : vid.className ? `.${vid.className.split(' ').join('.')}` : vid.tagName.toLowerCase();
                console.log(`[AIAnalyzer] Correlated stream to DOM selector: ${selector}`);

                const attr = vid.src ? 'src' : 'href';
                const scriptPattern = `
                     const el = document.querySelector('${selector}');
                     return el ? el.${attr} : null;
                 `;
                return this._buildRulePayload('dom_selector', 'dom', scriptPattern, targetUrl);
            }
        }
        return null;
    }

    static _buildRulePayload(strategy, subType, scriptText, targetUrl) {
        // Create a unique fingerprint hash for this specific rule structure
        const fingerprint = crypto.createHash('sha256').update(scriptText.trim()).digest('hex').substring(0, 16);
        return {
            id: `rule_${strategy}_${fingerprint}`,
            strategy,
            subType,
            scriptPattern: scriptText.trim(),
            sampleTarget: targetUrl,
            confidence: 0.85
        };
    }
}

module.exports = AIAnalyzer;
